### PR TITLE
Use relative imports

### LINKED ISSUE #5: Don't set PATH in Python code
While running the example notebook (https://github.com/AI4S2S/proto/blob/master/seasonal_mode.ipynb) I get an assertion error (`from RGCPD import RGCPD` fails because `main dir is not RGCPD dir`) upon import of RCGPC. It originates here: 

https://github.com/AI4S2S/proto/blob/0dd397f6101573544f10a55a4205e037e69acdfe/RGCPD/__init__.py#L9-L11

Not sure what's going on here, but I don't like it that this code is apparently changing my PATH settings. 

I'm guessing this is because otherwise later on the code will fail to import from certain modules. This can probably be solved by changing the folder structure and using relative imports.

### PR DESCRIPTION
**Pull request by Peter9192**
This PR changes the package structure so that we can use relative imports. This obviates the need for trickery like this:

https://github.com/AI4S2S/proto/blob/0dd397f6101573544f10a55a4205e037e69acdfe/RGCPD/__init__.py#L12-L17

After this I was finally able to run the import cell in the example notebook 😄 

closes #5 
closes #7

### CODE REVIEW

**Comment by semvijverberg** [comment]
Cool, I was wondering how to properly deal with these relative paths. Thanks!

**Comment by Peter9192** [comment]
Ah, yes, I guess I didn't encounter the imports that are inside functions or methods. I'll see if I can submit a fix today.

Thanks for reviewing anyway!

**Comment by Peter9192** [comment]
continued in #10

**Comment by Peter9192** [comment]
> In Cell 38 of subseasonal_mode.ipynb I not know how to load func_models.py.

`from RGCPD import find_precursors, plot_maps`

**Pull request merged**
